---
# apache portable runtime based native library install tasks

- block:
    - name: remove native apr library
      file:
        path: "{{ apr_libray_path }}"
        state: absent
      when: >-
        tomcat_force_install
        or tomcat_use_native_apr_library
           != ansible_local_facts.use_native_apr_library | default(false)
        or tomcat_java_home
           != ansible_local_facts.java_home | default("")
      register: tomcat_apr_remove_result
      vars:
        ansible_local_facts: >-
          {{ ansible_local["tomcat_" + tomcat_name] | default({}) }}

    - name: extract native apr library package
      unarchive:
        src: "{{ apr_library_package }}"
        dest: "{{ tomcat_native_apr_library_prefix_dir }}"
        copy: no
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        mode: "{{ tomcat_files_permissions }}"
        list_files: true
        creates: "{{ apr_libray_path }}"
      register: tomcat_apr_extract_package_result

    - block:
        - name: configure native apr library compilation
          shell: >-
            ./configure
            --with-apr={{ tomcat_apr_config_bin_path }}
            --with-java-home={{ tomcat_java_home }}
            --prefix={{ tomcat_native_apr_library_prefix_dir }}
          args:
            chdir: "{{ apr_library_src_dir }}"
            creates: "{{ apr_libray_path }}"

        - name: compile native apr library
          shell: make
          args:
            chdir: "{{ apr_library_src_dir }}"
            creates: "{{ apr_libray_path }}"

        - name: install native apr library
          shell: make install
          args:
            chdir: "{{ apr_library_src_dir }}"
            creates: "{{ apr_libray_path }}"
          register: tomcat_apr_install_result

        - name: clean native apr library extracted package
          file:
            path: "{{ apr_library_extraction_dir }}"
            state: absent
      when: tomcat_apr_extract_package_result.files is defined
  when:
    - tomcat_state in ["present", "started"]
    - tomcat_use_native_apr_library
    - ansible_facts.distribution_major_version is version("6", ">")
    - tomcat_version is version("7", ">=")
  vars:
    bin_dir: "{{ tomcat_home }}/bin"
    lib_dir: "{{ tomcat_home }}/lib"
    apr_libray_path: "{{ lib_dir }}/{{ tomcat_apr_libray_filename }}"
    apr_library_package: >-
      {{ bin_dir }}/{{ tomcat_apr_library_package_filename }}
    apr_library_extraction_dir: >-
      {{ bin_dir
         + "/"
         + tomcat_apr_extract_package_result.files
           | select("search", "README")
           | list
           | first
           | dirname }}
    apr_library_src_dir: >-
      {{ apr_library_extraction_dir
         + (tomcat_version is version("8", ">="))
           | ternary("/jni/native", "/native") }}
  tags:
    - role::tomcat
    - role::tomcat::install
    - role::tomcat::install::apr
