---
# apache portable runtime based native library install tasks

- block:
    # Usually apr library is a soft link to a specific version. Seems that not
    # all ansible modules manage in a consistent way broken links when using
    # `creates` argument. Some modules consider a broken sof link as an existent
    # file and another ones not. That's the reason we use here the `find`
    # module to get a consistent behaviour

    - name: Search installed apr library
      find:
        paths: "{{ tomcat_native_apr_library_dir }}"
        patterns: "{{ tomcat_apr_libray_patterns }}"
        file_type: any
      register: tomcat_apr_search_installed_result

    - name: Get info about installed apr library links
      stat:
        path: "{{ item.path }}"
      loop: >-
        {{ tomcat_apr_search_installed_result.files
           | selectattr("islnk", "equalto", true)
           | list }}
      loop_control:
        label: "{{ item.path }}"
      register: tomcat_apr_get_installed_links_result

    - name: Check installed apr library links
      stat:
        path: "{{ item.lnk_source }}"
      loop: >-
        {{ tomcat_apr_get_installed_links_result.results
           | map(attribute="stat")
           | list }}
      loop_control:
        label: "{{ item.path }}"
      register: tomcat_apr_check_installed_links_result

    - name: Remove native apr library
      file:
        path: "{{ item }}"
        state: absent
      when: >-
        tomcat_force_install | bool
        or tomcat_use_native_apr_library
           != ansible_local_facts.use_native_apr_library
              | default(tomcat_use_native_apr_library)
        or tomcat_java_home
           != ansible_local_facts.java_home
              | default(tomcat_java_home)
        or tomcat_apr_check_installed_links_result.results
           | map(attribute="stat")
           | selectattr("exists", "equalto", false)
           | list
           | length > 0
      notify:
        - restart tomcat
      loop: >-
        {{ tomcat_apr_search_installed_result.files
           | map(attribute="path")
           | list }}
      loop_control:
        label: "{{ item | basename }}"
      vars:
        ansible_local_facts: >-
          {{ ansible_local[tomcat_name] | default({}) }}

    - name: Extract native apr library package
      unarchive:
        src: "{{ apr_library_package }}"
        dest: "{{ tomcat_native_apr_library_dir }}"
        copy: no
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        mode: "{{ tomcat_file_permissions }}"
        list_files: yes
        creates: "{{ apr_libray_path }}"
      register: tomcat_apr_extract_package_result

    - block:
        - name: Search apr library compilation configure script
          find:
            paths: "{{ apr_library_extraction_dir }}"
            patterns: "configure"
            file_type: file
            recurse: yes
          register: tomcat_apr_search_configure_result

        - name: Configure native apr library compilation
          shell: >-
            ./configure
            --with-apr={{ tomcat_apr_config_bin_path }}
            --with-java-home={{ tomcat_java_home }}
            --prefix={{ tomcat_native_apr_library_dir }}
          args:
            chdir: "{{ apr_library_src_dir }}"
            creates: "{{ apr_libray_path }}"

        - name: Compile native apr library
          shell: make
          args:
            chdir: "{{ apr_library_src_dir }}"
            creates: "{{ apr_libray_path }}"

        - name: Search compiled apr library
          find:
            paths: "{{ apr_library_extraction_dir }}"
            patterns: "{{ tomcat_apr_libray_patterns }}"
            recurse: yes
            file_type: any
          register: tomcat_apr_search_compiled_result

        - block:
            - name: Install native apr library
              shell: "cp -dp {{ item }} {{ tomcat_native_apr_library_dir }}"
              args:
                creates: "{{ tomcat_native_apr_library_dir }}/{{ item }}"
              loop:  "{{ apr_files }}"
              loop_control:
                label: "{{ item | basename }}"
              notify:
                - restart tomcat

            - name: Setup native apr library files properties
              file:
                path: "{{ item }}"
                owner: "{{ tomcat_user }}"
                group: "{{ tomcat_group }}"
                mode: "{{ tomcat_file_permissions }}"
              loop:  "{{ apr_files }}"
              loop_control:
                label: "{{ item | basename }}"
          vars:
            apr_files: >-
              {{ tomcat_apr_search_compiled_result.files
                 | map(attribute='path')
                 | list }}

        - name: Clean native apr library extracted package
          file:
            path: "{{ apr_library_extraction_dir }}"
            state: absent
      when: tomcat_apr_extract_package_result.files is defined
  when:
    - tomcat_use_native_apr_library | bool
    - ansible_facts.distribution_major_version is version("6", ">")
    - tomcat_version is version("7", ">=")
  vars:
    apr_libray_path: >-
      {{ tomcat_native_apr_library_dir }}/{{ tomcat_apr_libray_filename }}
    apr_library_package: >-
      {{ tomcat_home }}/bin/{{ tomcat_apr_library_package_filename }}
    apr_library_extraction_dir: >-
      {{ tomcat_native_apr_library_dir
         + "/"
         + tomcat_apr_extract_package_result.files
           | select("search", "README")
           | list
           | first
           | dirname }}
    apr_library_src_dir: >-
      {{ tomcat_apr_search_configure_result.files[0].path | dirname }}
  tags:
    - role::tomcat
    - role::tomcat::install
    - role::tomcat::install::apr
