---
# Catalina scripts install tasks

- block:
    - name: install catalina startup scripts on instances
      synchronize:
        src: "{{ tomcat_instance_home }}/{{ item.1 }}"
        dest: "{{ tomcat_instance_base }}/{{ item.1 }}"
        archive: true
      loop: "{{ tomcat_catalina_scripts }}"

    - name: remove native daemon script for catalina based instances
      file:
        path: "{{ tomcat_instance_base }}/{{ item.1 }}"
        state: absent
      loop: "{{ tomcat_daemon_scripts }}"
  when:
    - tomcat_instance_state in ["present", "started"]
    - >-
      not tomcat_instance_use_native_daemon
      or tomcat_instance_version is version("7", "<")
  tags:
    - role::tomcat
    - role::tomcat::install
    - role::tomcat::install::catalina
