---
# Catalina scripts install tasks

- block:
    - name: Install catalina startup scripts
      synchronize:
        src: "{{ tomcat_home }}/{{ item }}"
        dest: "{{ tomcat_base }}/{{ item }}"
        archive: yes
      loop: "{{ tomcat_catalina_scripts }}"
      delegate_to: "{{ inventory_hostname }}"

    - name: Remove native daemon startup scripts
      file:
        path: "{{ tomcat_base }}/{{ item }}"
        state: absent
      loop: "{{ tomcat_daemon_scripts }}"
  when: not tomcat_use_native_daemon or tomcat_version is version("7", "<")
  tags:
    - role::tomcat
    - role::tomcat::install
    - role::tomcat::install::catalina
