---
# Commons Daemon install tasks

- block:
    - name: extract native daemon tarball
      unarchive:
        src: "{{ daemon_tarball }}"
        dest: "{{ instance_home }}/bin"
        copy: no
        owner: "{{ instance.user | default(tomcat_instance_user) }}"
        group: "{{ instance.group | default(tomcat_instance_group) }}"
        mode: "{{ tomcat_files_permissions }}"
        list_files: true
        creates: "{{ instance_home }}/bin/jsvc"
      register: tomcat_extract_daemon_tarball_result
      loop: "{{ tomcat_instances }}"
      loop_control:
        loop_var: instance
        label: "{{ instance.name }}"

    - block:
        - name: configure native daemon compilation
          shell: >-
            ./configure
            --with-java={{ instance.java_home
                           | default(tomcat_instance_java_home) }}
          args:
            chdir: "{{ daemon_src_dir }}"
            creates: "{{ instance_home }}/bin/jsvc"
          loop: "{{ tomcat_instances | flatten }}"
          loop_control:
            loop_var: instance
            index_var: index
            label: "{{ instance.name }}"

        - name: compile native daemon
          shell: make
          args:
            chdir: "{{ daemon_src_dir }}"
            creates: "{{ instance_home }}/bin/jsvc"
          loop: "{{ tomcat_instances | flatten }}"
          loop_control:
            loop_var: instance
            index_var: index
            label: "{{ instance.name }}"

        - name: install native daemon binary
          shell: "cp jsvc {{ instance_home }}/bin"
          args:
            chdir: "{{ daemon_src_dir }}"
            creates: "{{ instance_home }}/bin/jsvc"
          loop: "{{ tomcat_instances | flatten }}"
          loop_control:
            loop_var: instance
            index_var: index
            label: "{{ instance.name }}"

        - name: clean native daemon extracted tarball
          file:
            path: "{{ daemon_src_dir }}"
            state: absent
          loop: "{{ tomcat_instances | flatten }}"
          loop_control:
            loop_var: instance
            index_var: index
            label: "{{ instance.name }}"
      when: tomcat_extract_daemon_tarball_result is changed

    - name: install native daemon startup script on instances
      synchronize:
        src: "{{ instance_home }}/bin/daemon.sh"
        dest: "{{ instance_base }}/bin/daemon.sh"
        archive: true
      loop: "{{ tomcat_instances }}"
      loop_control:
        loop_var: instance
        label: "{{ instance.name }}"
      delegate_to: "{{ inventory_hostname }}"
  when:
    - instance.use_native_daemon | default(tomcat_instance_use_native_daemon)
    - instance.version is version("7", ">=")
  vars:
    instance_bin_dir: "{{ instance_home }}/bin"
    daemon_tarball:  >-
      {{ instance_bin_dir
         + "/"
         + "commons-daemon-native.tar.gz" }}
    daemon_src_dir: >-
      {{ instance_bin_dir
         + "/"
         + tomcat_extract_daemon_tarball_result.results[index].files
           | select("search", "README")
           | list
           | first
           | dirname
         + "/unix" }}
  tags:
    - role::tomcat
    - role::tomcat::install
    - role::tomcat::install::daemon
