---
# Role install tasks

- name: setup instances groups
  group:
    name: "{{ tomcat_instance_group }}"
    gid: "{{ tomcat_instance_group_gid) | default(omit) }}"
  when: tomcat_instance_state in ["present", "started"]
  tags:
    - role::tomcat
    - role::tomcat::install
    - role::tomcat::install::groups
