---
# Home directory install tasks

- block:
    - name: Setup tomcat home directory
      file:
        path: "{{ tomcat_home }}"
        state: directory
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        mode: "{{ tomcat_dir_permissions }}"

    - block:
        - name: Check tomcat home directory
          stat:
            path: "{{ tomcat_home }}/bin/catalina.sh"
          register: tomcat_home_check_result

        - include_tasks: artifact.yml
          vars:
            tomcat_artifact_state: "present"

        - name: Extract tomcat server package
          unarchive:
            src: "{{ tomcat_package }}"
            dest: "{{ tomcat_home }}"
            copy: no
            owner: "{{ tomcat_user }}"
            group: "{{ tomcat_group }}"
            extra_opts:
              - "--strip-components=1"
          register: tomcat_extract_daemon_package_result
          when: not tomcat_home_check_result.stat.exists
      when: >-
        tomcat_version
        is not version(ansible_local_facts.version | default(0), "==")
        or tomcat_force_install | bool
      vars:
        ansible_local_facts: >-
          {{ ansible_local[tomcat_name] | default({}) }}

    - name: Create tomcat home symlink
      file:
        src: "{{ tomcat_home }}"
        dest: "{{ tomcat_home_link }}"
        state: link
      when: tomcat_home_link is not none

    - include_tasks: artifact.yml
      vars:
        tomcat_artifact_state: "absent"

    - name: Setup tomcat home owner/group
      file:
        path: "{{ tomcat_home }}"
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        state: directory
      when: >-
        tomcat_user != ansible_local_facts.user | default(none)
        or tomcat_group != ansible_local_facts.group | default(none)
      vars:
        ansible_local_facts: >-
          {{ ansible_local[tomcat_name] | default({}) }}

    - name: Setup tomcat home directory tree
      file:
        path: "{{ tomcat_home }}/{{ item }}"
        state: directory
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        mode: "{{ tomcat_dir_permissions }}"
      register: tomcat_create_base_tree_result
      loop: "{{ tomcat_subdirs }}"
  tags:
    - role::tomcat
    - role::tomcat::install
    - role::tomcat::install::home
