---
# Instances install tasks

- block:
    - block:
        - name: setup instances base directory tree
          file:
            path: "{{ instance_base }}/{{ item.1 }}"
            state: directory
            owner: "{{ item.0.user | default(tomcat_instance_user) }}"
            group: "{{ item.0.group | default(tomcat_instance_group) }}"
            mode: "{{ tomcat_files_permissions }}"
          register: tomcat_create_instances_tree_result
          loop: >-
            {{ (tomcat_instances_state_present
                + tomcat_instances_state_started)
               | product(tomcat_instance_subdirs)
               | list }}
          loop_control:
            label: "{{ item.0.name }} {{ item.1 }}"

        - name: fill instances base directory tree
          synchronize:
            src: "{{ instance_home }}/{{ item.1.src }}"
            dest: "{{ instance_base }}/{{ item.1.dest }}"
            archive: true
            rsync_opts:
              - "--exclude='{{ tomcat_manager_config | dirname }}'"
          loop: >-
            {{ (tomcat_instances_state_present
                + tomcat_instances_state_started)
               | product(subdirs)
               | list }}
          loop_control:
            label: "{{ item.0.name }} {{ item.1.src }}"
          when: >-
            tomcat_extract_daemon_tarball_result.results
            | selectattr("instance.name", "equalto", item.0.name)
            | first
            is changed
            or tomcat_download_tomcat_tarball_result.results
            | selectattr("instance.name", "equalto", item.0.name)
            | first
            is changed
            or tomcat_create_instances_tree_result.results
            | selectattr("item.0.name", "equalto", item.0.name)
            | select("changed")
            | list
            | length > 0
          delegate_to: "{{ inventory_hostname }}"
          vars:
            subdirs:
              - src: conf/
                dest: conf
              - src: webapps/manager/
                dest: webapps/manager
      vars:
        instance: "{{ item.0 }}"

    - name: create additional files within instance tree
      include_role:
        name: amtega.files
      with_items: >-
        {{ tomcat_instances_state_present + tomcat_instances_state_started }}
      loop_control:
        loop_var: instance
      vars:
        files: "{{ instance.files | default(tomcat_instance_files) }}"
        files_prefix: "{{ instance_base }}"
  tags:
    - role::tomcat
    - role::tomcat::install
    - role::tomcat::install::instances
