---
# Instances install tasks

- block:
    - block:
        - name: setup instances base directory tree
          file:
            path: "{{ instance.base }}/{{ item.1 }}"
            state: directory
            owner: "{{ item.0.user | default(tomcat_instance_user) }}"
            group: "{{ item.0.group | default(tomcat_instance_group) }}"
            mode: "{{ tomcat_files_permissions }}"
          register: tomcat_create_instances_tree_result
          loop: >-
            {{ (tomcat_instances_state_present
                + tomcat_instances_state_started)
               | product(tomcat_instance_subdirs)
               | list }}
          loop_control:
            label: "{{ item.0.name }} {{ item.1 }}"

        - name: populate instances base directory tree
          synchronize:
            src: "{{ instance.home }}/{{ item.1 }}/"
            dest: "{{ instance.base }}/{{ item.1 }}"
            rsync_opts:
              - "--recursive"
              - "--links"
              - "--exclude='{{ tomcat_manager_config | dirname }}'"
              - "--update"
          loop: >-
            {{ (tomcat_instances_state_present
                + tomcat_instances_state_started)
               | product(tomcat_instance_subdirs_to_populate)
               | list }}
          loop_control:
            label: "{{ item.0.name }} {{ item.1 }}"
          delegate_to: "{{ inventory_hostname }}"
      vars:
        instance: "{{ item.0 }}"
  tags:
    - role::tomcat
    - role::tomcat::install
    - role::tomcat::install::instances
