---
# Instances install tasks

- block:
    - block:
        - name: setup instances base directory tree
          file:
            path: "{{ instance.base }}/{{ item.1 }}"
            state: directory
            owner: "{{ item.0.user | default(tomcat_instance_user) }}"
            group: "{{ item.0.group | default(tomcat_instance_group) }}"
            mode: "{{ tomcat_files_permissions }}"
          register: tomcat_create_instances_tree_result
          loop: >-
            {{ (tomcat_instances_state_present
                + tomcat_instances_state_started)
               | product(tomcat_instance_subdirs)
               | list }}
          loop_control:
            label: "{{ item.0.name }} {{ item.1 }}"

        - name: fill instances base directory tree
          synchronize:
            src: "{{ instance.home }}/{{ item.1 }}/"
            dest: "{{ instance.base }}/{{ item.1 }}"
            archive: true
            rsync_opts:
              - "--exclude='{{ tomcat_manager_config | dirname }}'"
          loop: >-
            {{ (tomcat_instances_state_present
                + tomcat_instances_state_started)
               | product(tomcat_instance_subdirs_to_populate)
               | list }}
          loop_control:
            label: "{{ item.0.name }} {{ item.1 }}"
          when: >-
            tomcat_extract_daemon_tarball_result.results
            | selectattr("instance.name", "equalto", item.0.name)
            | first
            is changed
            or tomcat_download_tomcat_tarball_result.results
            | selectattr("instance.name", "equalto", item.0.name)
            | first
            is changed
            or tomcat_create_instances_tree_result.results
            | selectattr("item.0.name", "equalto", item.0.name)
            | select("changed")
            | list
            | length > 0
          delegate_to: "{{ inventory_hostname }}"
      vars:
        instance: "{{ item.0 }}"
  tags:
    - role::tomcat
    - role::tomcat::install
    - role::tomcat::install::instances
