---
# Instances install tasks

- block:
    - name: setup instances base directory tree
      file:
        path: "{{ tomcat_instance_base }}/{{ item }}"
        state: directory
        owner: "{{ tomcat_instance_user }}"
        group: "{{ tomcat_instance_group }}"
        mode: "{{ tomcat_files_permissions }}"
      register: tomcat_create_instances_tree_result
      loop: "{{ tomcat_instance_subdirs }}"

    - name: populate instances base directory tree
      synchronize:
        src: "{{ tomcat_instance_home }}/{{ item.1 }}/"
        dest: "{{ tomcat_instance_base }}/{{ item.1 }}"
        archive: no
        rsync_opts:
          - "--recursive"
          - "--links"
          - "--update"
      loop: "{{ tomcat_instance_subdirs_to_populate) }}"
      delegate_to: "{{ inventory_hostname }}"
  when: tomcat_instance_state in ["present", "started"]
  tags:
    - role::tomcat
    - role::tomcat::install
    - role::tomcat::install::instances
