---
# Install tasks

- block:
    - import_tasks: "{{ role_path }}/tasks/install/packages.yml"
    - import_tasks: "{{ role_path }}/tasks/install/groups.yml"
    - import_tasks: "{{ role_path }}/tasks/install/users.yml"
    - import_tasks: "{{ role_path }}/tasks/install/server.yml"
    - import_tasks: "{{ role_path }}/tasks/install/instances.yml"
    - import_tasks: "{{ role_path }}/tasks/install/catalina.yml"
    - import_tasks: "{{ role_path }}/tasks/install/daemon.yml"
  tags:
    - role::tomcat
    - role::tomcat::install
