---
# Install tasks

- block:
    - include_tasks: "{{ role_path }}/tasks/install/home.yml"
      tags:
        - role::tomcat::install::home
    - include_tasks: "{{ role_path }}/tasks/install/base.yml"
      tags:
        - role::tomcat::install::base
    - include_tasks: "{{ role_path }}/tasks/install/daemon.yml"
      tags:
        - role::tomcat::install::daemon
    - include_tasks: "{{ role_path }}/tasks/install/apr.yml"
      tags:
        - role::tomcat::install::apr
    - include_tasks: "{{ role_path }}/tasks/install/catalina.yml"
      tags:
        - role::tomcat::install::catalina
    - include_tasks: "{{ role_path }}/tasks/install/check_mk.yml"
      tags:
        - role::tomcat::install::check_mk      
  tags:
    - role::tomcat
    - role::tomcat::install
