---
# Install tasks

- block:
    - include_tasks: "{{ role_path }}/tasks/install/packages.yml"
    - include_tasks: "{{ role_path }}/tasks/install/group.yml"
    - include_tasks: "{{ role_path }}/tasks/install/user.yml"
    - include_tasks: "{{ role_path }}/tasks/install/home.yml"
    - include_tasks: "{{ role_path }}/tasks/install/base.yml"
    - include_tasks: "{{ role_path }}/tasks/install/daemon.yml"
    - include_tasks: "{{ role_path }}/tasks/install/apr.yml"
    - include_tasks: "{{ role_path }}/tasks/install/catalina.yml"
  tags:
    - role::tomcat
    - role::tomcat::install
