---
# Install tasks

- block:
    - include_tasks: "{{ role_path }}/tasks/install/packages.yml"
    - include_tasks: "{{ role_path }}/tasks/install/groups.yml"
    - include_tasks: "{{ role_path }}/tasks/install/users.yml"
    - include_tasks: "{{ role_path }}/tasks/install/server.yml"
    - include_tasks: "{{ role_path }}/tasks/install/instances.yml"
    - include_tasks: "{{ role_path }}/tasks/install/daemon.yml"
  vars:
    instance_base: >-
      {{ instance.base
         | default(tomcat_instance_base
                   + "/"
                   + instance.name) }}
    instance_home: >-
      {{ instance.home
         | default(tomcat_instance_home
                   + "/apache-tomcat-"
                   + instance.version) }}
  tags:
    - role::tomcat
    - role::tomcat::install
