---
# Role install tasks

- block:
    - block:
        - name: install required operating system packages
          package:
            name: "{{ item }}"
            state: present
          loop: >-
            {{ tomcat_packages[distribution] | default([]) }}

        - name: install required python packages
          pip:
            name: "{{ item }}"
            state: "latest"
          loop: >-
            {{ tomcat_packages_python[distribution] | default([]) }}
      vars:
        distribution: >-
          {{ ansible_facts.distribution
             | lower
             + "_" + ansible_facts.distribution_major_version }}
      environment: "{{ tomcat_http_proxy_environment }}"
  tags:
    - role::tomcat
    - role::tomcat::install
    - role::tomcat::install::packages
