---
# Role install tasks

- block:
    # Seems that user module doesn't work correctly if you pass uid parameter
    # with an existen user (with no uid change) and there are processes running
    # with that user. So, first we check existence of the users as workaround

    - name: check required instance users
      shell: "getent passwd {{ tomcat_instance_user  }}"
      register: tomcat_check_users_result
      changed_when: false
      failed_when: false

    - name: setup instances users
      user:
        name: "{{ tomcat_instance_user }}"
        group: "{{ tomcat_instance_group }}"
        uid: >-
          {{ tomcat_instance_user_uid
             | default(tomcat_instance_user_uid)
             | default(omit) }}
      when: tomcat_check_users_result.rc != 0
  when: tomcat_instance_state in ["present", "started"]
  tags:
    - role::tomcat
    - role::tomcat::install
    - role::tomcat::install::users
