---
# Role install tasks

- block:
    # Seems that user module doesn't work correctly if you pass uid parameter
    # with an existen user (with no uid change) and there are processes running
    # with that user. So, first we check existence of the users as workaround

    - name: check required system user
      shell: "getent passwd {{ tomcat_user  }}"
      register: tomcat_check_users_result
      changed_when: no
      failed_when: no

    - name: setup system user
      user:
        name: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        uid: "{{ tomcat_user_uid | default(tomcat_user_uid) | default(omit) }}"
      when: tomcat_check_users_result.rc != 0
  tags:
    - role::tomcat
    - role::tomcat::install
    - role::tomcat::install::users
