---
# Uninstall ansible custom facts

- block:
    - name: uninstall tomcat facts
      file:
        path: /etc/ansible/facts.d/{{ instance.name }}.fact
        state: absent
      loop: "{{ tomcat_instances_state_absent }}"
      loop_control:
        loop_var: instance
        label: "{{ instance.name }}"

    - name: reload facts
      setup:
  tags:
    - role::tomcat
    - role::tomcat::uninstall
    - role::tomcat::uninstall::facts
