---
# Uninstall files tasks

- block:
    - name: Remove tomcat facts file
      file:
        path: "{{ tomcat_facts_file_path }}"
        state: absent

    - name: Remove tomcat logrotate file
      file:
        path: "{{ tomcat_logrotate_config_path }}"
        state: absent

    - name: Search tomcat files to uninstall
      find:
        paths:
          - "{{ tomcat_base }}"
          - "{{ tomcat_home }}"
        file_type: file
        recurse: no
      when: tomcat_state == "absent"
      register: tomcat_uninstall_search_files_result

    - name: Search tomcat directories to uninstall
      find:
        paths:
          - "{{ tomcat_base }}"
          - "{{ tomcat_home }}"
        file_type: directory
        recurse: yes
      when: tomcat_state == "absent"
      register: tomcat_uninstall_search_dirs_result

    - name: Uninstall tomcat files and directories
      file:
        path: "{{ item }}"
        state: absent
      when: item is not tomcat_startswith(exclusions)
      loop: "{{ files }}"
      vars:
        files: >-
          {{ (tomcat_uninstall_search_files_result.files
              + tomcat_uninstall_search_dirs_result.files)
             | map(attribute="path")
             | list }}
        exclusions: "{{ lookup('template', 'exclusions.yml.j2') | from_yaml }}"

    - name: Remove tomcat base directory if possible
      shell: "rmdir {{ tomcat_base }}"
      args:
        warn: no
      register: tomcat_uninstall_remove_base_result
      failed_when: no
      changed_when: tomcat_uninstall_remove_base_result.rc == 0

    - name: Remove tomcat home directory if possible
      shell: "rmdir {{ tomcat_home }}"
      args:
        warn: no
      register: tomcat_uninstall_remove_home_result
      failed_when: no
      changed_when: tomcat_uninstall_remove_home_result.rc == 0

    - name: Check tomcat home symlink
      stat:
        path: "{{ tomcat_home_link }}"
      register: tomcat_check_home_symlink
      when: tomcat_home_link is not none

    - name: Remove tomcat home symlink
      file:
        path: "{{ tomcat_home_link }}"
        state: absent
      when:
        - tomcat_home_link is not none
        - tomcat_check_home_symlink.stat.lnk_source is defined
        - tomcat_check_home_symlink.stat.lnk_source == tomcat_home

    - name: Check tomcat base symlink
      stat:
        path: "{{ tomcat_base_link }}"
      register: tomcat_check_base_symlink
      when: tomcat_base_link is not none

    - name: Remove tomcat base symlink
      file:
        path: "{{ tomcat_base_link }}"
        state: absent
      when:
        - tomcat_base_link is not none
        - tomcat_check_base_symlink.stat.lnk_source is defined
        - tomcat_check_base_symlink.stat.lnk_source == tomcat_base

    - name: Remove tomcat server package if possible
      file:
        path: "{{ tomcat_package }}"
        state: absent
  tags:
    - role::tomcat
    - role::tomcat::uninstall
    - role::tomcat::uninstall::files
