---
# Uninstall instances

- block:
    - name: search files to uninstall within tomcat instances base directory
      find:
        paths: "{{ instance_base }}"
        file_type: any
        recurse: yes
      register: tomcat_uninstall_instances_search_result
      loop: "{{ tomcat_instances_state_absent }}"
      loop_control:
        loop_var: instance
        label: "{{ instance.name }}"

    - name: uninstall instance files in base directory tree
      file:
        path: "{{ item.1.path }}"
        state: absent
      when: item.1.path is not tomcat_startswith(exclusions)
      loop: >-
        {{ tomcat_uninstall_instances_search_result.results
           | subelements('files') }}
      loop_control:
        index_var: index
        label: "{{ item.0.instance.name }} {{ item.1.path }}"
      vars:
        instance: "{{ item.0.instance }}"
        exclusions: >-
          {{ tomcat_instance_uninstall_preserve
             | map("regex_replace", "^(.*)", instance_base + "/\1")
             | list }}

    - name: remove instance base directory if possible
      shell: "rmdir {{ instance_base }}"
      args:
        warn: false
      register: tomcat_uninstall_instances_remove_base_result
      failed_when: false
      changed_when: tomcat_uninstall_instances_remove_base_result.rc == 0
      loop: "{{ tomcat_instances_state_absent }}"
      loop_control:
        loop_var: instance
        label: "{{ instance.name }}"

    - name: remove tomcat instance home if possible
      file:
        path: "{{ instance_home }}"
        state: absent
      when: instance_home not in lookup("template", "homes.j2") | from_yaml
      loop: "{{ tomcat_instances_state_absent }}"
      loop_control:
        loop_var: instance
        label: "{{ instance.name }}"

  tags:
    - role::tomcat
    - role::tomcat::uninstall
    - role::tomcat::uninstall::instances
