---
# Configuration tasks

- block:
    - include_tasks: "{{ role_path }}/tasks/uninstall/services.yml"
      tags:
        - role::tomcat::uninstall::services
    - include_tasks: "{{ role_path }}/tasks/uninstall/files.yml"
      tags:
        - role::tomcat::uninstall::files
  tags:
    - role::tomcat
    - role::tomcat::uninstall
