---
# Configuration tasks

- block:
    - import_tasks: "{{ role_path }}/tasks/uninstall/services.yml"
    - import_tasks: "{{ role_path }}/tasks/uninstall/instances.yml"
    - import_tasks: "{{ role_path }}/tasks/uninstall/facts.yml"
  tags:
    - role::tomcat
    - role::tomcat::uninstall
