---
# Uninstall services

- block:
    - name: disable and stop tomcat services
      service:
        name: "{{ tomcat_name }}"
        state: stopped
        enabled: false
      when: "'tomcat_' + tomcat_name in ansible_local"
      ignore_errors: true

    - block:
        - name: uninstall tomcat systemd services
          file:
            path: >-
              {{ tomcat_systemd_services_path
                 + "/"
                 + tomcat_name
                 + ".service" }}
            state: absent
          register: tomcat_remove_systemd_services_result

        - name: reload systemd
          command: systemctl daemon-reload
          when: tomcat_remove_systemd_services_result is changed
      when: ansible_facts.service_mgr == "systemd"

    - name: uninstall tomcat system v init services
      file:
        path: "{{ tomcat_systemv_init_path }}/{{ tomcat_name }}"
        state: absent
      when: ansible_facts.service_mgr != "systemd"
  tags:
    - role::tomcat
    - role::tomcat::uninstall
    - role::tomcat::uninstall::services
