---
# Uninstall services

- block:
    - name: Disable and stop tomcat services
      service:
        name: "{{ tomcat_name }}"
        state: stopped
        enabled: no
      when: tomcat_name in ansible_local
      ignore_errors: yes # noqa ignore-errors

    - block:
        - name: Uninstall tomcat systemd services
          file:
            path: >-
              {{ tomcat_systemd_services_path
                 + "/"
                 + tomcat_name
                 + ".service" }}
            state: absent
          register: tomcat_remove_systemd_services_result

        - name: Reload systemd
          command: systemctl daemon-reload
          when: tomcat_remove_systemd_services_result is changed
      when: ansible_facts.service_mgr == "systemd"

    - name: Uninstall tomcat system v init services
      file:
        path: "{{ tomcat_systemv_init_path }}/{{ tomcat_name }}"
        state: absent
      when: ansible_facts.service_mgr != "systemd"
  tags:
    - role::tomcat
    - role::tomcat::uninstall
    - role::tomcat::uninstall::services
