---
# Uninstall services

- block:
    - name: disable and stop tomcat instances
      service:
        name: "{{ tomcat_instance_name }}"
        state: stopped
        enabled: false
      when: ansible_local_facts is defined
      vars:
        ansible_local_facts: >-
          {{ ansible_local["tomcat_" + tomcat_instance_name] }}
      ignore_errors: true

    - block:
        - name: uninstall tomcat instances systemd services
          file:
            path: >-
              {{ tomcat_systemd_services_path
                 + "/"
                 + tomcat_instance_name
                 + ".service" }}
            state: absent
          register: tomcat_remove_systemd_services_result

        - name: reload systemd
          command: systemctl daemon-reload
          when: tomcat_remove_systemd_services_result is changed
      when: ansible_facts.service_mgr == "systemd"

    - name: uninstall tomcat instances system v init services
      file:
        path: "{{ tomcat_systemv_init_path }}/{{ tomcat_instance_name }}"
        state: absent
      when: ansible_facts.service_mgr != "systemd"
  when: tomcat_instance_state == "absent"
  tags:
    - role::tomcat
    - role::tomcat::uninstall
    - role::tomcat::uninstall::services
