---
# Role configuration task

- block:
    - name: setup tomcat instances environment variables
      template:
        src: setenv.sh.j2
        dest: "{{ instance.home}}/bin/setenv.sh"
        owner: "{{ instance.user | default(tomcat_instance_user) }}"
        group: "{{ instance.group | default(tomcat_instance_group) }}"
        mode: "{{ tomcat_files_permissions }}"
      loop: "{{ tomcat_instances }}"
      loop_control:
        loop_var: instance
        label: "{{ instance.name }}"

    - name: setup tomcat instances server config
      xml:
        path: "{{ item.0.home }}/conf/server.xml"
        xpath: "{{ item.1.xpath }}"
        value: "{{ item.1.value }}"
        pretty_print: true
      when: item.1.value in item.0
      loop: "{{ query('nested', tomcat_instances, config) }}"
      loop_control:
        label: "{{ item.0.name }} {{ item.1.value }} {{ item.0[item.1.value] }}"
      vars:
        connector_xpath: "/Server/Service[@name='Catalina']/Connector"
        config:
          - xpath: "/Server/port"
            value: server_port
          - xpath: "{{ connector_xpath }}[@protocol='HTTP/1.1']/port"
            value: server_http_port
          - xpath: "{{ connector_xpath }}[@protocol='HTTP/1.1']/redirectPort"
            value: server_https_port
          - xpath: "{{ connector_xpath }}[@sslProtocol='TLS']/port"
            value: server_http_port
          - xpath: "{{ connector_xpath }}[@protocol='AJP/1.3']/port"
            value: server_ajp_port
          - xpath: "{{ connector_xpath }}[@protocol='AJP/1.3']/redirectPort"
            value: server_https_port

    - name: configure tomcat facts
      template:
        src: tomcat.fact.j2
        dest: /etc/ansible/facts.d/tomcat.fact
        mode: 0640
  tags:
    - role::tomcat
    - role::tomcat::configure
