---
# Role install tasks

- block:
    - name: install required packages
      package:
        name: "{{ item }}"
        state: present
      loop: >-
        {{ tomcat_packages[distribution] }}
      vars:
        distribution: >-
          {{ ansible_facts.distribution
             | lower
             + "_" + ansible_facts.distribution_major_version }}

    - block:
        - name: download tomcat tarball
          get_url:
            url: >-
              {{ tomcat_download_url | default(tomcat_default_download_url) }}
            dest: "{{ tomcat_download_path }}"
          environment:
            http_proxy: "{{ tomcat_http_proxy }}"
            https_proxy: "{{ tomcat_https_proxy }}"
            http_no_proxy: "{{ tomcat_http_no_proxy }}"

        - name: extract tomcat tarball installation directory
          unarchive:
            src: "{{ tomcat_download_path }}/{{ tomcat_download_tarball }}"
            dest: "{{ tomcat_base_path }}"
            copy: no

        - name: create symlink to the installation directory
          file:
            src: "{{ tomcat_home }}"
            dest: "{{ tomcat_link }}"
            state: link
            mode: "u=rwx,go=rx"

        - name: create custom fact directory
          file:
            path: /etc/ansible/facts.d
            state: "directory"

        - name: insert custom fact file
          template:
            src: tomcat.fact.j2
            dest: /etc/ansible/facts.d/tomcat.fact
            mode: 0640
      when: >-
        ansible_local.tomcat is undefined
        or tomcat_version is version(ansible_local.tomcat.version, ">")

    - name: delete downloaded tomcat tarball
      file:
        path: "{{ tomcat_download_path }}/{{ tomcat_download_tarball }}"
        state: absent
      when: tomcat_download_remove
  tags:
    - role::tomcat
    - role::tomcat::install
