---
# Role tasks

- name: sanity checks
  import_tasks: check/main.yml
  tags:
    - role::tomcat
    - role::tomcat::check

- name: uninstall tomcat
  import_tasks: uninstall/main.yml
  tags:
    - role::tomcat
    - role::tomcat::uninstall

- name: install tomcat
  import_tasks: install/main.yml
  tags:
    - role::tomcat
    - role::tomcat::install

- name: configure tomcat
  import_tasks: configure/main.yml
  tags:
    - role::tomcat
    - role::tomcat::configure

- name: setup tomcat service
  import_tasks: service/main.yml
  tags:
    - role::tomcat
    - role::tomcat::service
