---
# Role tasks

- name: sanity checks
  include_tasks: check/main.yml
  tags:
    - role::tomcat
    - role::tomcat::check

- name: uninstall tomcat
  include_tasks: uninstall/main.yml
  tags:
    - role::tomcat
    - role::tomcat::uninstall
  when: tomcat_state == "absent"

- block:
    - name: install tomcat
      include_tasks: install/main.yml
      tags:
        - role::tomcat
        - role::tomcat::install

    - name: configure tomcat
      include_tasks: configure/main.yml
      tags:
        - role::tomcat
        - role::tomcat::configure

    - name: setup tomcat service
      include_tasks: service/main.yml
      tags:
        - role::tomcat
        - role::tomcat::service
  when: tomcat_state in ["present", "started"]
