---
# Role tasks

- name: do some sanity checks
  import_tasks: check.yml
  tags:
    - role::tomcat
    - role::tomcat::check

- name: install tomcat
  import_tasks: install.yml
  tags:
    - role::tomcat
    - role::tomcat::install

- name: configure tomcat
  import_tasks: install.yml
  tags:
    - role::tomcat
    - role::tomcat::configure
