---
# Role service tasks

- block:
    - block:
        - name: setup tomcat instances systemd services
          template:
            src: "systemd.service.j2"
            dest: >-
              {{ tomcat_systemd_services_path
                 + "/tomcat@"
                 + instance.name
                 + ".service" }}
            owner: root
            group: root
            mode: 0644
          register: tomcat_setup_systemd_services_result
          loop: "{{ tomcat_instances }}"
          loop_control:
            loop_var: instance
            label: "{{ instance.name }}"

        - name: reload systemd
          command: systemctl daemon-reload
          changed_when: false
          when: >-
            tomcat_setup_systemd_services_result.results
            | select("changed")
            | list
            | length > 0
      when: ansible_facts.service_mgr == "systemd"

    - name: setup tomcat instances system v init services
      template:
        src: "sysvinit.j2"
        dest: "{{ tomcat_systemv_init_path }}/tomcat@{{ instance.name }}"
        owner: root
        group: root
        mode: 0755
      when: ansible_facts.service_mgr != "systemd"
      loop: "{{ tomcat_instances }}"
      loop_control:
        loop_var: instance
        label: "{{ instance.name }}"

    - name: enable and start tomcat instances
      service:
        name: "tomcat@{{ instance.name }}"
        state: started
        enabled: true
      loop: "{{ tomcat_instances }}"
      loop_control:
        loop_var: instance
        label: "{{ instance.name }}"

  vars:
    instance_base: >-
      {{ instance.base
         | default(tomcat_instance_base)
           + "/"
           + instance.name }}
  tags:
    - role::tomcat
    - role::tomcat::service
