---
# Role handlers

- name: Restart tomcat service
  service:
    name: "{{ tomcat_name }}"
    state: restarted
    enabled: yes
  listen: restart tomcat
  tags:
    - role::tomcat
    - role::tomcat::restart
