---

dependency:
  name: galaxy
driver:
  name: docker
lint: "${MOLECULE_SCENARIO_DIRECTORY}/../resources/linters.sh"
platforms:
  - name: "centos7-${INSTANCE_UUID:-1}"
    image: centos:7
    dockerfile: ../resources/Dockerfile.j2
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "fedora32-${INSTANCE_UUID:-1}"
    image: fedora:32
    dockerfile: ../resources/Dockerfile.j2
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_32
  - name: "fedora33-${INSTANCE_UUID:-1}"
    image: fedora:33
    dockerfile: ../resources/Dockerfile.j2
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_33
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/converge.yml
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
          tomcat_name: server1
          tomcat_version: 9.0.41
          tomcat_home: /opt/apache-tomcat-9.0.41
          tomcat_base: /srv/tomcat/server1
          tomcat_link: /opt/tomcat9
          tomcat_server_port: 8005
          tomcat_server_http_port: 8080
          tomcat_server_https_port: 8443
          tomcat_server_ajp_port: 8009
          tomcat_manager_addresses_allow:
            - 192.168.5.2
            - 192.168.5.3
          tomcat_manager_addresses_deny:
            - 192.168.5.13
            - 192.168.5.14
          tomcat_manager_hostnames_allow:
            - host1.acme.com
            - host2.acme.com
          tomcat_manager_hostnames_deny:
            - badhost1.acme.com
            - badhost2.acme.com
          tomcat_realm:
            className: org.apache.catalina.realm.LockOutRealm
          tomcat_subrealms:
            - className: org.apache.catalina.realm.UserDatabaseRealm
              resourceName: UserDatabase
          tomcat_cluster: yes
      molecule_hosts_fedora_33:
        vars:
          tomcat_java_setup: no          
verifier:
  name: ansible
