---
# Cluster configuration tasks

- block:
    - name: create cluster section in server config
      xml:
        path: "{{ tomcat_instance_base }}/{{ tomcat_server_config }}"
        xpath: "{{ cluster_xpath }}"
        attribute: "channelSendOptions"
        value: "{{ tomcat_instance_cluster_channel_send_options) }}"
        state: present
        pretty_print: true

    - name: setup cluster section properties in server config
      xml:
        path: "{{ tomcat_instance_base }}/{{ tomcat_server_config }}"
        xpath: "{{ cluster_xpath }}"
        set_children: >-
          {{ lookup('template', 'cluster.yml.j2') | from_yaml }}
        input_type: yaml
        pretty_print: true
      register: tomcat_configure_cluster_result
  when:
    - tomcat_instance_state in ["present", "started"]
    - tomcat_instance_cluster
  vars:
    service_xpath: "/Server/Service[@name='Catalina']"
    engine_xpath: "{{ service_xpath }}/Engine[@name='Catalina']"
    host_xpath: "{{ engine_xpath }}/Host[@name='localhost']"
    cluster_xpath: >-
      {{ host_xpath
         + "/Cluster"
         + "[@className='org.apache.catalina.ha.tcp.SimpleTcpCluster']" }}
  tags:
    - role::tomcat
    - role::tomcat::configure
    - role::tomcat::configure::cluster
