---
# Contained managed security configuration tasks

- name: setup tomcat contained managed security groups
  template:
    src: "cms.xml.j2"
    dest: "{{ instance_base }}/{{ tomcat_users_config }}"
    owner: "{{ instance.user | default(tomcat_instance_user) }}"
    group: "{{ instance.group | default(tomcat_instance_group) }}"
    mode: 0755
  register: tomcat_configure_cms_result
  loop: "{{ tomcat_instances }}"
  loop_control:
    loop_var: instance
    label: "{{ instance.name }}"

  tags:
    - role::tomcat
    - role::tomcat::configure
    - role::tomcat::configure::cms
