---
# Contained managed security configuration tasks

- block:
    - name: Configure tomcat user database
      xml:
        path: "{{ tomcat_base }}/{{ tomcat_server_config }}"
        xpath: "/Server/GlobalNamingResources/Resource[@name='UserDatabase']"
        attribute: readonly
        value: "true"
        pretty_print: yes
      notify:
        - restart tomcat

    - name: Setup contained managed security roles and users
      template:
        src: "tomcat-users.xml.j2"
        dest: "{{ tomcat_base }}/{{ tomcat_users_config }}"
        owner: "{{ tomcat_user | default(tomcat_user) }}"
        group: "{{ tomcat_group | default(tomcat_group) }}"
        mode: "{{ tomcat_file_permissions }}"
      notify:
        - restart tomcat
  tags:
    - role::tomcat
    - role::tomcat::configure
    - role::tomcat::configure::cms
