---
# Environment variables configuration tasks

- name: Setup tomcat environment variables
  template:
    src: setenv.sh.j2
    dest: "{{ tomcat_base }}/bin/setenv.sh"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: "{{ tomcat_executable_permissions }}"
  notify:
    - restart tomcat
  tags:
    - role::tomcat
    - role::tomcat::configure
    - role::tomcat::configure::environment
