---
# Environment variables configuration tasks

- name: setup tomcat environment variables
  template:
    src: setenv.sh.j2
    dest: "{{ tomcat_base }}/bin/setenv.sh"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: "{{ tomcat_files_permissions }}"
  tags:
    - role::tomcat
    - role::tomcat::configure
    - role::tomcat::configure::environment
