---
# Ansible custom facts configuration tasks

- block:
    - name: create custom facts directory
      file:
        path: /etc/ansible/facts.d
        state: "directory"

    - name: configure tomcat facts
      template:
        src: "tomcat.fact.j2"
        dest: /etc/ansible/facts.d/tomcat.fact
        owner: root
        group: root
        mode: 0640

    - name: reload facts
      setup:
  tags:
    - role::tomcat
    - role::tomcat::configure
    - role::tomcat::configure::facts
