---
# Tomcat user limits configuration tasks

- name: setup tomcat user limits
  template:
    src: "limits.conf.j2"
    dest: "{{ tomcat_limits_config }}/10-{{ instance.name }}.conf"
    owner: root
    group: root
    mode: 0644
  loop: "{{ tomcat_instances_state_present + tomcat_instances_state_started }}"
  loop_control:
    loop_var: instance
    label: "{{ instance.name }}"
  tags:
    - role::tomcat
    - role::tomcat::configure
    - role::tomcat::configure::limits
