---
# Logrotate configuration tasks

- name: create logrotate configuration file
  template:
    src: logrotate.j2
    dest: "{{ tomcat_logrotate_config_path }}"
  tags:
    - role::tomcat
    - role::tomcat::configure
    - role::tomcat::configure::logrotate
