---
# Configuration tasks

- block:
    - import_tasks: "{{ role_path }}/tasks/configure/environment.yml"
    - import_tasks: "{{ role_path }}/tasks/configure/server.yml"
    - import_tasks: "{{ role_path }}/tasks/configure/cms.yml"
    - import_tasks: "{{ role_path }}/tasks/configure/manager.yml"
    - import_tasks: "{{ role_path }}/tasks/configure/cluster.yml"
    - import_tasks: "{{ role_path }}/tasks/configure/facts.yml"
  tags:
    - role::tomcat
    - role::tomcat::configure
