---
# Configuration tasks

- block:
    - import_tasks: "{{ role_path }}/tasks/configure/environment.yml"
    - import_tasks: "{{ role_path }}/tasks/configure/server.yml"
    - import_tasks: "{{ role_path }}/tasks/configure/cms.yml"
    - import_tasks: "{{ role_path }}/tasks/configure/manager.yml"
    - import_tasks: "{{ role_path }}/tasks/configure/cluster.yml"
    - import_tasks: "{{ role_path }}/tasks/configure/limits.yml"
    - import_tasks: "{{ role_path }}/tasks/configure/facts.yml"
  vars:
    instance_base: >-
      {{ instance.base
         | default(tomcat_instance_base
                   + "/"
                   + instance.name) }}
    instance_home: >-
      {{ instance.home
         | default(tomcat_instance_home
                   + "/apache-tomcat-"
                   + instance.version) }}
    instance_pid: >-
      {{ instance_base }}/{{ instance.pid_file
                             | default(tomcat_instance_pid_file) }}
  tags:
    - role::tomcat
    - role::tomcat::configure
