---
# Manager configuration tasks

- name: setup tomcat manager
  template:
    src: "manager.xml.j2"
    dest: "{{ instance.base }}/{{ tomcat_manager_config }}"
    owner: "{{ instance.user | default(tomcat_instance_user) }}"
    group: "{{ instance.group | default(tomcat_instance_group) }}"
    mode: 0755
  register: tomcat_configure_manager_result
  loop: "{{ tomcat_instances_state_present + tomcat_instances_state_started }}"
  loop_control:
    loop_var: instance
    label: "{{ instance.name }}"
  tags:
    - role::tomcat
    - role::tomcat::configure
    - role::tomcat::configure::manager
