---
# Manager configuration tasks

- name: Setup tomcat manager
  template:
    src: "manager.xml.j2"
    dest: "{{ tomcat_base }}/{{ tomcat_manager_config }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: "{{ tomcat_conf_permissions }}"
  notify:
      - restart tomcat
  tags:
    - role::tomcat
    - role::tomcat::configure
    - role::tomcat::configure::manager
