---
# Manager configuration tasks

- name: setup tomcat manager
  template:
    src: "manager.xml.j2"
    dest: "{{ tomcat_instance_base }}/{{ tomcat_manager_config }}"
    owner: "{{ tomcat_instance_user }}"
    group: "{{ tomcat_instance_group }}"
    mode: 0755
  register: tomcat_configure_manager_result
  when: tomcat_instance_state in ["present", "started"]
  tags:
    - role::tomcat
    - role::tomcat::configure
    - role::tomcat::configure::manager
