---
# Tasks to setup application dirs

- block:
    - name: read configured realms
      xml:
        path: "{{ instance.base }}/{{ tomcat_server_config }}"
        xpath: >-
          {{ "/Server/Service[@name='Catalina']/Engine[@name='Catalina']"
                    "/Realm" }}
        content: attribute
      register: tomcat_read_realms_result
      loop: >-
        {{ tomcat_instances_state_present
           + tomcat_instances_state_started }}
      loop_control:
        loop_var: instance
        label: "{{ instance.name }}"

    - name: setup realms
      xml:
        path: "{{ realm_path }}"
        xpath: >-
          {{ (not realm_attribute_to_remove)
             | ternary(realm_xpath_base,
                       realm_xpath_base
                       + "/@"
                       + realm_attribute) }}
        attribute: >-
          {{ (not realm_attribute_to_remove)
             | ternary(realm_attribute, omit) }}
        value: "{{ realm_attribute_value | string }}"
        state: >-
          {{ (not realm_attribute_to_remove)
             | ternary("present", "absent") }}
        pretty_print: true
      register: tomcat_setup_realm_result
      loop: >-
        {{ query('subelements',
                 lookup('template', 'realms.yml.j2') | from_yaml,
                 'attributes_names') }}
      loop_control:
        label: "{{ realm_path }} {{ item.0.name }} {{ item.1 }}"
      vars:
        realm_path: "{{ item.0.base }}/{{ tomcat_server_config }}"
        service_xpath: "/Server/Service[@name='Catalina']"
        engine_xpath: "{{ service_xpath }}/Engine[@name='Catalina']"
        realm_xpath_base: "{{ engine_xpath }}/Realm[@name='{{ item.0.name }}']"
        realm_attribute: "{{ item.1 }}"
        realm_attribute_value: "{{ item.0.attributes_values[item.1] }}"
        realm_attribute_to_remove: "{{ realm_attribute_value is none }}"

    - name: remove realms
      xml:
        path: "{{ item.0.instance.base }}/{{ tomcat_server_config }}"
        xpath: >-
          {{ "/Server/Service[@name='Catalina']/Engine[@name='Catalina']"
             "/Realm[@name='" + item.1.Realm.name + "'" }}
        state: absent
        pretty_print: true
      register: tomcat_remove_realm_result
      when: >-
        item.1.Realm.name is defined
        and item.1.Realm.name
            not in item.0.instance.realms | map(attribute='name') | list
      loop: >-
        {{ query('subelements',
                 tomcat_read_realms_result.results,
                 'matches') }}
      loop_control:
        label: >-
          {{ item.0.name }}
          {{ item.1.Realm.name | default(item.1.Realm.className) }}
  tags:
    - role::tomcat
    - role::tomcat::configure
    - role::tomcat::configure::realms
