---
# Realms configuration tasks

- block:
    - name: setup tomcat realm
      xml:
        path: "{{ tomcat_base }}/{{ tomcat_server_config }}"
        xpath: >-
          {{ (not realm_attribute_to_remove)
             | ternary(realm_xpath_base,
                       realm_xpath_base
                       + "/@"
                       + realm_attribute) }}
        attribute: >-
          {{ (not realm_attribute_to_remove)
             | ternary(realm_attribute, omit) }}
        value: "{{ realm_value | string }}"
        state: >-
          {{ (not realm_attribute_to_remove)
             | ternary("present", "absent") }}
        pretty_print: true
      register: tomcat_configure_realm_result
      when: tomcat_realm is defined
      loop: "{{ tomcat_realm.keys() }}"
      vars:
        service_xpath: "/Server/Service[@name='Catalina']"
        engine_xpath: "{{ service_xpath }}/Engine[@name='Catalina']"
        realm_xpath_base: "{{ engine_xpath }}/Realm"
        realm_attribute: "{{ item }}"
        realm_value: "{{ tomcat_realm[item] }}"
        realm_attribute_to_remove: "{{ realm_attribute_value is none }}"

    - name: setup tomcat subrealms
      xml:
        path: "{{ tomcat_base }}/{{ tomcat_server_config }}"
        xpath: >-
          /Server/Service[@name='Catalina']/Engine[@name='Catalina']/Realm
        set_children: "{{ lookup('template', 'subrealms.yml.j2') | from_yaml }}"
        input_type: yaml
        state: present
        pretty_print: true
      register: tomcat_configure_subrealms_result

    - name: remove tomcat realm
      xml:
        path: "{{ tomcat_base }}/{{ tomcat_server_config }}"
        xpath: >-
          /Server/Service[@name='Catalina']/Engine[@name='Catalina']/Realm
        state: absent
        pretty_print: true
      register: tomcat_remove_realm_result
      when: tomcat_realm is not defined or tomcat_realm is none

    - name: remove tomcat subrealms
      xml:
        path: "{{ tomcat_base }}/{{ tomcat_server_config }}"
        xpath: >-
          /Server/Service[@name='Catalina']/Engine[@name='Catalina']/Realm/Realm
        state: absent
        pretty_print: true
      register: tomcat_remove_subrealms_result
      when:
        - tomcat_realm is defined
        - tomcat_subrealms is not defined
  tags:
    - role::tomcat
    - role::tomcat::configure
    - role::tomcat::configure::realms
