---
# Realms configuration tasks

- block:
    - name: Setup tomcat realm
      xml:
        path: "{{ tomcat_base }}/{{ tomcat_server_config }}"
        xpath: >-
          {{ (not realm_attribute_to_remove)
             | ternary(realm_xpath_base,
                       realm_xpath_base
                       + "/@"
                       + realm_attribute) }}
        attribute: >-
          {{ (not realm_attribute_to_remove)
             | ternary(realm_attribute, omit) }}
        value: >-
          {{ (not realm_attribute_to_remove)
             | ternary(realm_value | string, omit) }}
        state: >-
          {{ (not realm_attribute_to_remove)
             | ternary("present", "absent") }}
        pretty_print: yes
      when: tomcat_realm is not none
      notify:
        - restart tomcat
      loop: "{{ tomcat_realm.keys() | list }}"
      loop_control:
        label: "{{ realm_attribute }} {{ realm_value }}"
      vars:
        service_xpath: "/Server/Service[@name='Catalina']"
        engine_xpath: "{{ service_xpath }}/Engine[@name='Catalina']"
        realm_xpath_base: "{{ engine_xpath }}/Realm"
        realm_attribute: "{{ item }}"
        realm_value: "{{ tomcat_realm[item] }}"
        realm_attribute_to_remove: "{{ tomcat_realm[item] is none }}"

    - name: Setup tomcat subrealms
      xml:
        path: "{{ tomcat_base }}/{{ tomcat_server_config }}"
        xpath: >-
          /Server/Service[@name='Catalina']/Engine[@name='Catalina']/Realm
        set_children: "{{ lookup('template', 'subrealms.yml.j2') | from_yaml }}"
        input_type: yaml
        state: present
        pretty_print: yes
      notify:
        - restart tomcat

    - name: Remove tomcat realm
      xml:
        path: "{{ tomcat_base }}/{{ tomcat_server_config }}"
        xpath: >-
          /Server/Service[@name='Catalina']/Engine[@name='Catalina']/Realm
        state: absent
        pretty_print: yes
      when: tomcat_realm is none
      notify:
        - restart tomcat

    - name: Remove tomcat subrealms
      xml:
        path: "{{ tomcat_base }}/{{ tomcat_server_config }}"
        xpath: >-
          /Server/Service[@name='Catalina']/Engine[@name='Catalina']/Realm/Realm
        state: absent
        pretty_print: yes
      when: >-
        (tomcat_realm is not none and tomcat_subrealms is none)
        or tomcat_subrealms is none
        or tomcat_subrealms | length == 0
      notify:
        - restart tomcat
  tags:
    - role::tomcat
    - role::tomcat::configure
    - role::tomcat::configure::realms
