---
# Server configuration tasks

- name: setup tomcat server config
  xml:
    path: "{{ tomcat_base }}/{{ tomcat_server_config }}"
    xpath: >-
      {{ (value is not none)
         | ternary(item.xpath, item.xpath + "/@" + item.attribute) }}
    attribute: >-
      {{ (value is not none)
         | ternary(item.attribute, omit) }}
    value: >-
      {{ (value is not none)
         | ternary(value_string, omit) }}
    state: >-
      {{ (value is not none)
         | ternary(omit, "absent") }}
    pretty_print: yes
  notify:
    - restart tomcat
  loop: "{{ config }}"
  loop_control:
    label: >-
      {{ item.xpath }}
      {{ item.attribute }}
  vars:
    service_xpath: "/Server/Service[@name='Catalina']"
    connector_xpath: "{{ service_xpath }}/Connector"
    engine_xpath: "{{ service_xpath }}/Engine[@name='Catalina']"
    host_xpath: "{{ engine_xpath }}/Host[@name='localhost']"
    value: "{{ lookup('vars', item.value) }}"
    value_string: >-
      {{ (value is sameas(true) or value is sameas(false))
         | ternary(value | string | lower, value | string) }}
    config:
      - xpath: "/Server"
        attribute: port
        value: tomcat_server_port
      - xpath: "{{ connector_xpath }}[@protocol='HTTP/1.1']"
        attribute: port
        value: tomcat_server_http_port
      - xpath: "{{ connector_xpath }}[@protocol='HTTP/1.1']"
        attribute: redirectPort
        value: tomcat_server_https_port
      - xpath: "{{ connector_xpath }}[@protocol='HTTP/1.1']"
        attribute: enableLookups
        value: tomcat_server_enable_lookups
      - xpath: "{{ connector_xpath }}[@protocol='AJP/1.3']"
        attribute: port
        value: tomcat_server_ajp_port
      - xpath: "{{ connector_xpath }}[@protocol='AJP/1.3']"
        attribute: maxThreads
        value: tomcat_server_ajp_max_threads
      - xpath: "{{ connector_xpath }}[@protocol='AJP/1.3']"
        attribute: redirectPort
        value: tomcat_server_https_port
      - xpath: "{{ host_xpath }}"
        attribute: autoDeploy
        value: tomcat_server_autodeploy
      - xpath: "{{ engine_xpath }}"
        attribute: jvmRoute
        value: tomcat_server_engine_jvm_route
  tags:
    - role::tomcat
    - role::tomcat::configure
    - role::tomcat::configure::server
