---
# Server instances configuration tasks

- name: setup tomcat instances server config
  xml:
    path: "{{ instance_base }}/{{ tomcat_server_config }}"
    xpath: >-
      {{ (value != "<NONE/>")
         | ternary(item.1.xpath, item.1.xpath + "/@" + item.1.attribute) }}
    attribute: >-
      {{ (value != "<NONE/>")
         | ternary(item.1.attribute, omit) }}
    value: >-
      {{ (value != "<NONE/>")
         | ternary(valuestr, omit) }}
    state: >-
      {{ (value != "<NONE/>")
         | ternary(omit, "absent") }}
    pretty_print: true
  register: tomcat_configure_server_result

  loop: "{{ tomcat_instances | product(config) | list }}"
  loop_control:
    label: >-
      {{ item.0.name }}
      {{ item.1.xpath }}
      {{ item.1.attribute }}
  vars:
    instance: "{{ item.0 }}"
    service_xpath: "/Server/Service[@name='Catalina']"
    connector_xpath: "{{ service_xpath }}/Connector"
    engine_xpath: "{{ service_xpath }}/Engine[@name='Catalina']"
    host_xpath: "{{ engine_xpath }}/Host[@name='localhost']"
    value: >-
      {{ instance[item.1.value]
         | default(lookup('vars',
                          'tomcat_instance_'
                          + item.1.value, default="<NONE/>")) }}
    valuestr: >-
      {{ (value is sameas(true) or value is sameas(false))
         | ternary(value | string | lower, value | string) }}
    config:
      - xpath: "/Server"
        attribute: port
        value: server_port
      - xpath: "{{ connector_xpath }}[@protocol='HTTP/1.1']"
        attribute: port
        value: server_http_port
      - xpath: "{{ connector_xpath }}[@protocol='HTTP/1.1']"
        attribute: redirectPort
        value: server_https_port
      - xpath: "{{ connector_xpath }}[@sslProtocol='TLS']"
        attribute: port
        value: server_http_port
      - xpath: "{{ connector_xpath }}[@protocol='AJP/1.3']"
        attribute: port
        value: server_ajp_port
      - xpath: "{{ connector_xpath }}[@protocol='AJP/1.3']"
        attribute: maxThreads
        value: server_ajp_max_threads
      - xpath: "{{ connector_xpath }}[@protocol='AJP/1.3']"
        attribute: redirectPort
        value: server_https_port
      - xpath: "{{ host_xpath }}"
        attribute: autoDeploy
        value: server_autodeploy
      - xpath: "{{ engine_xpath }}"
        attribute: jvmRoute
        value: server_engine_jvm_route
  tags:
    - role::tomcat
    - role::tomcat::configure
    - role::tomcat::configure::server
