---

dependency:
  name: galaxy
driver:
  name: docker
lint: "${MOLECULE_SCENARIO_DIRECTORY}/../resources/linters.sh"
platforms:
  - name: "centos7-${INSTANCE_UUID:-1}"
    image: centos:7
    dockerfile: ../resources/Dockerfile.j2
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "centos8-${INSTANCE_UUID:-1}"
    image: centos:8
    dockerfile: ../resources/Dockerfile.j2
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_8      
  - name: "fedora32-${INSTANCE_UUID:-1}"
    image: fedora:32
    dockerfile: ../resources/Dockerfile.j2
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_32
  - name: "fedora33-${INSTANCE_UUID:-1}"
    image: fedora:33
    dockerfile: ../resources/Dockerfile.j2
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_33
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/converge.yml
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
          tomcat_name: server3
          tomcat_version: 9.0.44
          tomcat_home: /opt/apache-tomcat-9.0.44
          tomcat_base: /srv/tomcat/server3
          tomcat_use_native_daemon: no
          tomcat_use_native_apr_library: no
          tomcat_java_variables:
            var1: VAR1
            var2: VAR2
          tomcat_server_port: 8007
          tomcat_server_http_port: 8082
          tomcat_server_https_port: 8445
          tomcat_server_ajp_port: 8011
          tomcat_server_ajp_max_threads: 800
          tomcat_server_engine_jvm_route: tomcat-server-3
          tomcat_link: /opt/tomcat7
          tomcat_artifact:
            type: http
            host: http://archive.apache.org
            path: /dist/tomcat/tomcat-9/v9.0.44/bin
            file: apache-tomcat-9.0.44.tar.gz
            dest: /tmp
          tomcat_realm:
            className: org.apache.catalina.realm.LockOutRealm
          tomcat_subrealms:
            - className: org.apache.catalina.realm.UserDatabaseRealm
              resourceName: UserDatabase
      molecule_hosts_fedora_33:
        vars:
          tomcat_java_setup: no
verifier:
  name: ansible
