---
# Role check tasks

- block:
    - name: assert platform is supported
      assert:
        that:
          - distribution in tomcat_supported_distributions
          - >-
            ansible_facts.distribution_version
            is version(tomcat_supported_versions[distribution], ">=")
      vars:
        distribution: "{{ ansible_facts.distribution | lower }}"

    - name: assert default instance state is supported
      assert:
        that:
          - tomcat_instance_state in ['started', 'present', 'absent']

    - name: assert instances state is supported
      assert:
        that:
          - instance.state in ['started', 'present', 'absent']
      loop: "{{ tomcat_instances }}"
      loop_control:
        loop_var: instance
        label: "{{ instance.name }}"
  tags:
    - role::tomcat
    - role::tomcat::check
