---
# Role check tasks

- block:
    - name: assert platform is supported
      assert:
        that:
          - distribution in tomcat_supported_distributions
          - >-
            ansible_facts.distribution_version
            is version(tomcat_supported_versions[distribution], ">=")
      vars:
        distribution: "{{ ansible_facts.distribution | lower }}"

    - name: assert state is supported
      assert:
        that:
          - tomcat_state in ['started', 'present', 'absent']
  tags:
    - role::tomcat
    - role::tomcat::check
