---
# Role service tasks

- block:
    - name: Disable and stop tomcat
      service:
        name: "{{ tomcat_name }}"
        state: stopped
        enabled: no
      when: tomcat_state == "present"

    - name: Enable and start tomcat
      service:
        name: "{{ tomcat_name }}"
        state: started
        enabled: yes
      when: tomcat_state == "started"
  tags:
    - role::tomcat
    - role::tomcat::service
    - role::tomcat::service::common
