---
# Install tasks

- block:
    - include_tasks: "{{ role_path }}/tasks/service/systemd.yml"
    - include_tasks: "{{ role_path }}/tasks/service/systemv.yml"
    - include_tasks: "{{ role_path }}/tasks/service/instances.yml"
  vars:
    instance_base: >-
      {{ instance.base
         | default(tomcat_instance_base
                   + "/"
                   + instance.name) }}
  tags:
    - role::tomcat
    - role::tomcat::service
