---
# Install tasks

- block:
    - include_tasks: "{{ role_path }}/tasks/service/systemd.yml"
    - include_tasks: "{{ role_path }}/tasks/service/systemv.yml"
    - include_tasks: "{{ role_path }}/tasks/service/common.yml"
  tags:
    - role::tomcat
    - role::tomcat::service
