---
# SystemV service tasks

- name: setup tomcat system v init services
  template:
    src: "sysvinit.j2"
    dest: "{{ tomcat_systemv_init_path }}/{{ tomcat_name }}"
    owner: root
    group: root
    mode: 0755
  when:
    - tomcat_state in ["present", "started"]
    - ansible_facts.service_mgr != "systemd"
  tags:
    - role::tomcat
    - role::tomcat::service
    - role::tomcat::service::systemv
