---
# Systemd service tasks

- block:
    - name: Setup tomcat systemd services
      template:
        src: "systemd.service.j2"
        dest: >-
          {{ tomcat_systemd_services_path
             + "/"
             + tomcat_name
             + ".service" }}
        owner: root
        group: root
        mode: 0644
      register: tomcat_setup_systemd_services_result
      notify:
        - restart tomcat

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes
      when: tomcat_setup_systemd_services_result is changed
  when: ansible_facts.service_mgr == "systemd"
  tags:
    - role::tomcat
    - role::tomcat::service
    - role::tomcat::service::systemd
