---
# SystemV service tasks

- name: setup tomcat instances system v init services
  template:
    src: "sysvinit.j2"
    dest: "{{ tomcat_systemv_init_path }}/{{ instance.name }}"
    owner: root
    group: root
    mode: 0755
  when: ansible_facts.service_mgr != "systemd"
  loop: "{{ tomcat_instances }}"
  loop_control:
    loop_var: instance
    label: "{{ instance.name }}"
  tags:
    - role::tomcat
    - role::tomcat::service
    - role::tomcat::service::systemv
