---
# Systemd service tasks

- block:
    - name: setup tomcat instances systemd services
      template:
        src: "systemd.service.j2"
        dest: >-
          {{ tomcat_systemd_services_path
             + "/"
             + instance.name
             + ".service" }}
        owner: root
        group: root
        mode: 0644
      register: tomcat_setup_systemd_services_result
      when: instance.state | default(tomcat_instance_state) == "present"
      loop: "{{ tomcat_instances }}"
      loop_control:
        loop_var: instance
        label: "{{ instance.name }}"

    - name: reload systemd
      command: systemctl daemon-reload
      when: >-
        tomcat_setup_systemd_services_result.results
        | select("changed")
        | list
        | length > 0
  when: ansible_facts.service_mgr == "systemd"
  tags:
    - role::tomcat
    - role::tomcat::service
    - role::tomcat::service::systemd
